[23.12.14] 알고리즘 문제 풀이
dlfeksgo/algorithm pull request #2
Opened 2023-12-14 14:38 UTC by dlfeksgo

@f-lab-jake 
멘토님, 새로운 문제 풀이 6개 PR 올립니다!

2023-12-14 23:59 UTC, f-lab-jake requested changes

2023-12-14 23:59 UTC, f-lab-jake commented on 00.baekjoon/027-13305.ts
> +    if (oilPrice > price[i + 1]) oilPrice = price[i + 1];
`Math.min`을 활용해봅시다

2023-12-14 23:59 UTC, f-lab-jake commented on 00.baekjoon/028-1931.ts
> +for (let i = 1; i < n; i++) {
1부터 순회를해야하니 `for(... of ...)`을 못쓴것으로 짐작합니다. `slice`를 활용해보세요.

2023-12-14 23:59 UTC, f-lab-jake commented on 00.baekjoon/028-1931.ts
> +let endTime = times[0][1];
계속 `[1]`같은 방식으로 참조해야한다면 차라리 튜플이 아니라 레코드로 만드는 것도 방법입니다.

2023-12-14 23:59 UTC, f-lab-jake commented on 02.programmers-Lv1/002-체육복.ts
> +    }
시간복잡도가 얼마인가요?

2023-12-16 09:13 UTC, dlfeksgo reviewed
@f-lab-jake 
멘토님 리뷰를 달았었는데  이번에는 `Submit` 하지 않으면 등록이 되지 않네요. 다시 등록해보았습니다.

2023-12-16 13:33 UTC, f-lab-jake commented on 02.programmers-Lv1/002-체육복.ts
> +    }
좀더 효율적으로 풀어봅시다

2023-12-16 13:33 UTC, f-lab-jake commented on 00.baekjoon/028-1931.ts
> +for (let i = 1; i < n; i++) {
네 이렇게하면 됩니다

2023-12-16 13:33 UTC, f-lab-jake commented on 00.baekjoon/027-13305.ts
> +    if (oilPrice > price[i + 1]) oilPrice = price[i + 1];
전체 코드를 보여주시겠어요?

2023-12-16 13:50 UTC, dlfeksgo commented on 00.baekjoon/027-13305.ts
> +    if (oilPrice > price[i + 1]) oilPrice = price[i + 1];
```typescript
const [, d, p]: string[] = require('fs')
    .readFileSync('input.txt')
    .toString()
    .trim()
    .split('\n');

const distances = d.split(' ').map((v) => BigInt(v));
const price = p.split(' ').map(Number);

let answer = BigInt(0);
let oilPrice = BigInt(0);

for (const [i, distance] of distances.entries()) {
    if (Math.min(...price.slice(0, i + 1)) === price[i]) {
        oilPrice = BigInt(price[i]);
    }
    answer += oilPrice * distance;
}

console.log(String(answer));

```
`Math.min`을 사용하기 위해 price는 number로 변환했습니다.
그리고 순회 시점까지의 price를 자른 것 중 최솟값인 경우로 분기했더니 예제는 잘 통과하는데 제출하면 오답이라고 합니다.

2023-12-17 05:21 UTC, f-lab-jake commented on 00.baekjoon/027-13305.ts
> +    if (oilPrice > price[i + 1]) oilPrice = price[i + 1];
지금 코드는 BigInt 문제를 떠나(왜 관련있는지 아직 이해못했습니다)
비교가 매우 비효율적입니다. `Math.min(...price.slice(0, i + 1))` 이부분이 복잡도를 제곱시킵니다.

2023-12-17 07:01 UTC, dlfeksgo commented
@f-lab-jake 
멘토님 3문제 개선해보았습니다.

- BigInt 문제는 제가 접근 자체를 잘못했었습니다. 총합만 BigInt를 적용했습니다.

2023-12-18 05:37 UTC, f-lab-jake requested changes

2023-12-18 05:37 UTC, f-lab-jake commented on 02.programmers-Lv1/002-체육복.ts
> +    for (const v of students) v >= 1 && answer++;
`answer++`도 변경이라는 효과를 발생시키는 것입니다.
그리고 아예 좀더 함수형으로 짤수있습니다.

2023-12-18 05:37 UTC, f-lab-jake commented on 00.baekjoon/027-13305.ts
> +    price[i] = oilPrice;
`price`를 변경하지 않도록 해보세요.

2023-12-18 06:16 UTC, dlfeksgo commented on 02.programmers-Lv1/002-체육복.ts
> +    for (const v of students) v >= 1 && answer++;
사용할 수 있는 메서드가 떠오르지 않아 별도 함수를 만들어 분리해보았습니다.

2023-12-18 08:38 UTC, f-lab-jake requested changes

2023-12-18 08:38 UTC, f-lab-jake commented on 02.programmers-Lv1/002-체육복.ts
> +        const result = student === 0 && compare(i);
`compare`를 호출하면 효과가 발생하지요?
그리고 비교만 하는게 아닌데 이런 이름을 지어주는건 위험합니다.

2023-12-18 09:13 UTC, dlfeksgo commented on 02.programmers-Lv1/002-체육복.ts
> +        const result = student === 0 && compare(i);
문으로 변경하면서 `isPossible` 변수명에 맞게 반환값의 타입을 boolean으로 맞춰보았는데 `student === 0`도 `checkAndChangeQuantity` 함수 내에서 처리하는 것이 더 나을까요?

2023-12-18 09:17 UTC, f-lab-jake requested changes

2023-12-18 09:17 UTC, f-lab-jake commented on 02.programmers-Lv1/002-체육복.ts
> +        if (student === 0) isPossible = checkAndChangeQuantity(i);
`isPossible`은 약간 이상하죠. 왜냐면 이미 `students[i - 1]`에 대한 변경을 저질렀잖아요? `isTransferred`가 낫겠네요. 그리고 `checkAndChangeQuantity`가 `students[i]`를 변경하는 동작을 포함하지 않는것도 위험합니다. `checkAndChangeQuantity` 이거만 따로부르면 전체 체육복 수가 늘어나버리잖아요? 혼자서 제구실을 못하는 거죠.

문제를 분해하려는 시도는 아주 좋습니다. 이 한문제에 대해서도 여러가지 시도를 해보면서 배운게 있을겁니다.

올바로 분해하려면 그 방향이 중요합니다. `transferUniform(index1, index2)`란 함수를 만들고 활용해봅시다.

2023-12-18 09:57 UTC, dlfeksgo commented on 02.programmers-Lv1/002-체육복.ts
> +        if (student === 0) isPossible = checkAndChangeQuantity(i);
빌릴 수 있는 이전/이후 학생 index를 매개변수로 받아 분기하고, 함수 내에서 빌린 학생의 수량도 변경할 수 있도록 했습니다. `for…of`문으로 하려는 바가 명확해졌습니다.

2023-12-18 10:38 UTC, f-lab-jake requested changes

2023-12-18 10:38 UTC, f-lab-jake commented on 02.programmers-Lv1/002-체육복.ts
> +    const transferUniform = (beforeIdx: number, afterIdx: number) => {
지금 구현은 함수로 따로 빼기엔 너무 특수한 동작아닌가요?
`beforeIndex`에서 `afterIndex`로 체육복을 옮겨야합니다.

2023-12-19 01:55 UTC, f-lab-jake requested changes

2023-12-19 01:55 UTC, f-lab-jake commented on 02.programmers-Lv1/002-체육복.ts
>      };
`transferUniform(index1, index2)`는 `index1`에 여유분이 있으면 `index2`에게 하나 준다.

라는 의미를 가져야합니다. 지금 구현은 그 의미를 잘 반영하지 못합니다. 최대 2개이상 체육복을 가지고잇을수 있다고 생각하고 짜면, 오히려 더 자연스럽게 될겁니다.

2023-12-19 02:48 UTC, dlfeksgo commented on 02.programmers-Lv1/002-체육복.ts
>      };
최대 2개를 가질 수 있다는 점에만 신경썼던 것 같습니다. 다시 수정했습니다!

2023-12-19 03:10 UTC, f-lab-jake requested changes

2023-12-19 03:10 UTC, f-lab-jake commented on 02.programmers-Lv1/002-체육복.ts
>          students[lostIdx] = 1;
```ts
students[reserveIdx] = 1;
students[lostIdx] = 1;
```
요게 하나를 건내준다는 의미로 읽힐까요? 의미를 떠나 체육복 2개 이상 갖고있다면 틀린코드가 되겠죠.

2023-12-19 03:26 UTC, dlfeksgo commented on 02.programmers-Lv1/002-체육복.ts
>          students[lostIdx] = 1;
1개를 감소시키는 식으로 변경했습니다!

2023-12-19 05:06 UTC, f-lab-jake approved these changes
네 이제 비로소, for문에서는 없으면 빌리는 시도만 하고, `transferUniform`에서는 빌려줄수있으면 빌려주는 동작만 하게 되었습니다. 이런 형태가 왜 좋은지 이해가 가시나요?

2023-12-19 05:54 UTC, dlfeksgo commented
넵! 함수 호출 조건이 명확하고, 관련 로직들은 함수 내에서 종료되어 각 구문에서 처리하려는 바가 잘 구분됩니다. 코드 변경 과정을 기억해두겠습니다. 감사합니다.

2023-12-19 05:54 UTC, merged